### ISSUE TITLE
Missing Manual Pages?

### ISSUE THREAD

**Issue by Urrova** [taedixon/boosters-lab#32] opened 2021-05-09 15:30 UTC
Hi! I was looking the BL manual, and its like... half of the pages are missing. Its there any place to download these missing pages, or just the pages dont exists? Thanks.

**Comment by Urrova** [comment] 2021-05-09 15:37
Uh, i found the pages, but the program tries to open a page in /help//pagename.html so the program cant show the pages on it

**Comment by taedixon** [comment] 2021-05-09 16:20
I think there are better sources of information on modding nowadays anyway but yeah. I created "stubs" for a bunch of pages that I wanted to include but never got around to writing 😔

**Comment by Leo40Git** [comment] 2021-05-13 14:08
Closed as duplicate of #3.

**Closed by Leo40Git** 2021-05-13 14:08 UTC
